import pandas as pd

df = pd.read_csv('data/trial_params.csv')

# for i, v in enumerate(sorted(df['param_name'].unique())):
    # print(f"{i}: '{v}',")

mapping = {
      0: 'balancing:strategy',
      1: 'classifier:__choice__',
      2: 'classifier:adaboost:algorithm_v2',
      3: 'classifier:adaboost:learning_rate',
      4: 'classifier:adaboost:max_depth',
      5: 'classifier:adaboost:n_estimators',
      6: 'classifier:bernoulli_nb:alpha',
      7: 'classifier:bernoulli_nb:fit_prior',
      8: 'classifier:decision_tree:criterion_v2',
      9: 'classifier:decision_tree:max_depth_factor',
     10: 'classifier:decision_tree:max_features',
     11: 'classifier:decision_tree:max_leaf_nodes',
     12: 'classifier:decision_tree:min_impurity_decrease',
     13: 'classifier:decision_tree:min_samples_leaf',
     14: 'classifier:decision_tree:min_samples_split',
     15: 'classifier:decision_tree:min_weight_fraction_leaf',
     16: 'classifier:extra_trees:bootstrap',
     17: 'classifier:extra_trees:criterion_v2',
     18: 'classifier:extra_trees:max_depth',
     19: 'classifier:extra_trees:max_features',
     20: 'classifier:extra_trees:max_leaf_nodes',
     21: 'classifier:extra_trees:min_impurity_decrease',
     22: 'classifier:extra_trees:min_samples_leaf',
     23: 'classifier:extra_trees:min_samples_split',
     24: 'classifier:extra_trees:min_weight_fraction_leaf',
     25: 'classifier:extra_trees:n_estimators',
     26: 'classifier:k_nearest_neighbors:n_neighbors',
     27: 'classifier:k_nearest_neighbors:p',
     28: 'classifier:k_nearest_neighbors:weights',
     29: 'classifier:lda:shrinkage_factor',
     30: 'classifier:lda:shrinkage_v2',
     31: 'classifier:lda:tol',
     32: 'classifier:liblinear_svc:C',
     33: 'classifier:liblinear_svc:dual',
     34: 'classifier:liblinear_svc:fit_intercept',
     35: 'classifier:liblinear_svc:intercept_scaling',
     36: 'classifier:liblinear_svc:loss',
     37: 'classifier:liblinear_svc:multi_class',
     38: 'classifier:liblinear_svc:penalty',
     39: 'classifier:liblinear_svc:tol',
     40: 'classifier:libsvm_svc:C',
     41: 'classifier:libsvm_svc:coef0',
     42: 'classifier:libsvm_svc:degree',
     43: 'classifier:libsvm_svc:gamma',
     44: 'classifier:libsvm_svc:kernel',
     45: 'classifier:libsvm_svc:max_iter',
     46: 'classifier:libsvm_svc:shrinking',
     47: 'classifier:libsvm_svc:tol',
     48: 'classifier:mlp:activation',
     49: 'classifier:mlp:alpha',
     50: 'classifier:mlp:batch_size',
     51: 'classifier:mlp:beta_1',
     52: 'classifier:mlp:beta_2',
     53: 'classifier:mlp:early_stopping',
     54: 'classifier:mlp:epsilon',
     55: 'classifier:mlp:hidden_layer_depth',
     56: 'classifier:mlp:learning_rate_init',
     57: 'classifier:mlp:n_iter_no_change',
     58: 'classifier:mlp:num_nodes_per_layer',
     59: 'classifier:mlp:shuffle',
     60: 'classifier:mlp:solver',
     61: 'classifier:mlp:tol',
     62: 'classifier:mlp:validation_fraction',
     63: 'classifier:multinomial_nb:alpha',
     64: 'classifier:multinomial_nb:fit_prior',
     65: 'classifier:passive_aggressive:C',
     66: 'classifier:passive_aggressive:average',
     67: 'classifier:passive_aggressive:fit_intercept',
     68: 'classifier:passive_aggressive:loss',
     69: 'classifier:passive_aggressive:tol',
     70: 'classifier:qda:reg_param',
     71: 'classifier:random_forest:bootstrap',
     72: 'classifier:random_forest:criterion_v2',
     73: 'classifier:random_forest:max_depth',
     74: 'classifier:random_forest:max_features',
     75: 'classifier:random_forest:max_leaf_nodes',
     76: 'classifier:random_forest:min_impurity_decrease',
     77: 'classifier:random_forest:min_samples_leaf',
     78: 'classifier:random_forest:min_samples_split',
     79: 'classifier:random_forest:min_weight_fraction_leaf',
     80: 'classifier:random_forest:n_estimators',
     81: 'classifier:sgd:alpha',
     82: 'classifier:sgd:average',
     83: 'classifier:sgd:epsilon',
     84: 'classifier:sgd:eta0',
     85: 'classifier:sgd:fit_intercept',
     86: 'classifier:sgd:l1_ratio',
     87: 'classifier:sgd:learning_rate',
     88: 'classifier:sgd:loss_v2',
     89: 'classifier:sgd:penalty',
     90: 'classifier:sgd:power_t',
     91: 'classifier:sgd:tol',
     92: 'data_preprocessor:__choice__',
     93: 'data_preprocessor:feature_type:numerical_transformer:imputation:strategy',
     94: 'data_preprocessor:feature_type:numerical_transformer:rescaling:__choice__',
     95: 'data_preprocessor:feature_type:numerical_transformer:rescaling:quantile_transformer:n_quantiles',
     96: 'data_preprocessor:feature_type:numerical_transformer:rescaling:quantile_transformer:output_distribution',
     97: 'data_preprocessor:feature_type:numerical_transformer:rescaling:robust_scaler:q_max',
     98: 'data_preprocessor:feature_type:numerical_transformer:rescaling:robust_scaler:q_min',
     99: 'feature_preprocessor:__choice__',
    100: 'feature_preprocessor:extra_trees_preproc_for_classification:bootstrap',
    101: 'feature_preprocessor:extra_trees_preproc_for_classification:criterion_v2',
    102: 'feature_preprocessor:extra_trees_preproc_for_classification:max_depth',
    103: 'feature_preprocessor:extra_trees_preproc_for_classification:max_features',
    104: 'feature_preprocessor:extra_trees_preproc_for_classification:max_leaf_nodes',
    105: 'feature_preprocessor:extra_trees_preproc_for_classification:min_impurity_decrease',
    106: 'feature_preprocessor:extra_trees_preproc_for_classification:min_samples_leaf',
    107: 'feature_preprocessor:extra_trees_preproc_for_classification:min_samples_split',
    108: 'feature_preprocessor:extra_trees_preproc_for_classification:min_weight_fraction_leaf',
    109: 'feature_preprocessor:extra_trees_preproc_for_classification:n_estimators',
    110: 'feature_preprocessor:fast_ica:algorithm',
    111: 'feature_preprocessor:fast_ica:fun',
    112: 'feature_preprocessor:fast_ica:n_components',
    113: 'feature_preprocessor:fast_ica:whiten_v2',
    114: 'feature_preprocessor:feature_agglomeration:linkage',
    115: 'feature_preprocessor:feature_agglomeration:metric_v2',
    116: 'feature_preprocessor:feature_agglomeration:n_clusters',
    117: 'feature_preprocessor:feature_agglomeration:pooling_func',
    118: 'feature_preprocessor:kitchen_sinks:gamma',
    119: 'feature_preprocessor:kitchen_sinks:n_components',
    120: 'feature_preprocessor:liblinear_svc_preprocessor:C',
    121: 'feature_preprocessor:liblinear_svc_preprocessor:dual',
    122: 'feature_preprocessor:liblinear_svc_preprocessor:fit_intercept',
    123: 'feature_preprocessor:liblinear_svc_preprocessor:intercept_scaling',
    124: 'feature_preprocessor:liblinear_svc_preprocessor:loss',
    125: 'feature_preprocessor:liblinear_svc_preprocessor:multi_class',
    126: 'feature_preprocessor:liblinear_svc_preprocessor:penalty',
    127: 'feature_preprocessor:liblinear_svc_preprocessor:tol',
    128: 'feature_preprocessor:nystroem_sampler:coef0',
    129: 'feature_preprocessor:nystroem_sampler:degree',
    130: 'feature_preprocessor:nystroem_sampler:gamma',
    131: 'feature_preprocessor:nystroem_sampler:kernel',
    132: 'feature_preprocessor:nystroem_sampler:n_components',
    133: 'feature_preprocessor:pca:keep_variance',
    134: 'feature_preprocessor:pca:whiten',
    135: 'feature_preprocessor:polynomial:degree',
    136: 'feature_preprocessor:polynomial:include_bias',
    137: 'feature_preprocessor:polynomial:interaction_only',
    138: 'feature_preprocessor:random_trees_embedding:max_depth',
    139: 'feature_preprocessor:random_trees_embedding:max_leaf_nodes',
    140: 'feature_preprocessor:random_trees_embedding:min_samples_leaf',
    141: 'feature_preprocessor:random_trees_embedding:min_samples_split',
    142: 'feature_preprocessor:random_trees_embedding:min_weight_fraction_leaf_v2',
    143: 'feature_preprocessor:random_trees_embedding:n_estimators',
    144: 'feature_preprocessor:select_percentile_classification:percentile',
    145: 'feature_preprocessor:select_percentile_classification:score_func',
    146: 'feature_preprocessor:select_rates_classification:alpha',
    147: 'feature_preprocessor:select_rates_classification:mode',
    148: 'feature_preprocessor:select_rates_classification:score_func',
}

reversed = {v: k for k, v in mapping.items()}
df['param_name'] = df['param_name'].map(lambda x: reversed.get(x))

# print(df[df[['trial_id', 'param_name']].duplicated()])

wide = (df.pivot_table(index='trial_id',
                       columns='param_name',
                       values='param_value',
                       aggfunc='first')
          .rename_axis(None, axis=1))

trials = pd.read_csv('data/trials.csv').loc[:, ['study_id', 'trial_id', 'value']]

print(wide.shape)
wide.join(trials.set_index('trial_id')).dropna(subset=['value']).to_csv('data/trial_params_wide.csv')