type: development
development:
  redis:
    host: redis://localhost
    # host: dfki-3112.dfki.de
    port: 6379
    api: b840fc02d524045429941cc15f59e41cb7be6c52
  postgresql:
    host: localhost
    port: 5432
    password: d71cf9cc-5126-4b11-abe3-01b5ed1ec95b
  secrets:
    github:
      client_id: 4667e052695ee0a38872
      client_secret: 19fd9bfb0a8266f6fd474046f6c0e4f71d550fa0
  fs:
    data: /home/reds/myrepo/dorian/data/